# Generated by Django 4.0.3 on 2022-03-19 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('admin', models.CharField(max_length=30)),
                ('desc', models.CharField(max_length=500)),
                ('admin_email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventname', models.CharField(default='', max_length=122, null=True)),
                ('location', models.CharField(default='', max_length=15, null=True)),
                ('startDate', models.DateTimeField(default='', null=True)),
                ('nop', models.IntegerField()),
                ('dec', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=30)),
                ('position', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=122)),
                ('contactnumber', models.CharField(default='', max_length=122)),
                ('part_email', models.EmailField(default='', max_length=254)),
                ('eventName', models.CharField(max_length=122)),
                ('reg_type', models.CharField(default='', max_length=20)),
                ('number', models.IntegerField()),
            ],
        ),
    ]
